### ISSUE TITLE
why default connect database is test

### ISSUE THREAD

**Issue by infeng** [mongolass/mongolass#12]
```javascript
var Mongolass = require('mongolass');
var mongolass = new Mongolass();
mongolass.connect(undefined);
```

When the connection string is `undefined`, I hold it throw error, but it connect `test` database actually.

**Comment by nswbmw** [comment]
```
mongolass.connect(undefined);
```

equal to

```
mongolass.connect();
```

so, connected to default `localhost:27017/test`.

**Comment by infeng** [comment]
Why not throw error when connection string is `undefined`, connected to default `localhost:27017/test` is troubling.

**Comment by nswbmw** [comment]
welcome pr~
