### ISSUE TITLE
model不能指定为数组类型？

### ISSUE THREAD

**Issue by pihat** [mongolass/mongolass#18]
这是需要写入 mongodb 的 json 字符串
`{"name":"","udid":"","desp":"","theme":"theme2","media":["平板广告","不要998，只要799"]}`
下面是 nodejs 里写法
```
exports.Devices = mongolass.model('Devices', {
    name: { type: 'string' },
    udid: { type: 'string' },
    desp: { type: 'string' },
    theme: { type: 'string' },
    media: { type: 'arrays' }
})
```
结果爆出这个错误：
`Error: ($.media: ["平板广告","不要998，只要799"]) ✖ ({"type":"arrays"})`
请问 mongolass 不能支持数组类型吗？

**Comment by nswbmw** [comment]
`media: { type: 'arrays' }` -> `media: { type: 'array' }`

**Comment by ghostcode** [comment]
@nswbmw 就算改了也同样的错。

**Comment by nswbmw** [comment]
@ghostcode 看上面更新了

**Comment by ghostcode** [comment]
@nswbmw 嗯，我在 https://github.com/mongolass/mongolass/issues/32 这个 issue 找到了答案。但是感觉这种方式很别扭，`media: [{ type: 'string' }]` 这里的 string 是代表 media 里元素的类型？还有这种情况下， media 为 required 如何写？大家对定义数组的方式有点模糊，其他定义数组相关的issue：https://github.com/mongolass/mongolass/issues/23。
