### ISSUE TITLE
关于find()中使用$in 查询报错

### ISSUE THREAD

**Issue by ZJH9Rondo** [mongolass/mongolass#20]
```
 var collect = User.findOne({_id: author},{collections: 1,_id: 0}).exec();

        var collections = collect.collections;

        return  Post
        .find({_id: {$in: collections}})
```
代码如上
collections 确定是数组形式

报错 : Unhandled rejection MongoError: $in needs an array
找了很多看了；不知道错在哪里，或者说能否有其他办法传入参数，而不强制写成 $in: [ '**' , '***'...]这种形式

因为我这块参数是查询到的

麻烦大佬帮看看，感激不尽。

**Comment by nswbmw** [comment]
> collections 确定是数组形式

console.log 打印，贴出来看下

**Comment by ZJH9Rondo** [comment]
![image](https://user-images.githubusercontent.com/19373822/26915356-46e731a4-4c58-11e7-9607-ea6efa12e3ec.png)

这个返回的查询数组
我是这样写的，出现了问题
例如：
查询出的数组如上，然后直接 find( _id: author,{ $in: collections})
其中 collections 就是上面的返回的结果，我就是想将返回的结果直接作为一个参数用 $in 进行查询，这个参数当然满足数组类型，请问有没有什么解决办法？

**Comment by ZJH9Rondo** [comment]
非常抱歉，这个刚才弄明白了，出错的原因是对mongolass查询返回结果工作机制的不够理解倒置的，要使用查询结果，但是没有使用return返回查询的值，直接将查询语句赋给了变量，所以出现错误，可能自我解释的理解程度还不够到位，望指正
Ps: 问题已解决，感谢回复。
