### ISSUE TITLE
请问afterFind: async function和afterFind: function有什么区别?谢谢

### ISSUE THREAD

**Issue by yuanyuanyuan** [mongolass/mongolass#21]

**Comment by nswbmw** [comment]
async function 里可以用 await，像 generator function 里可以用 yield 似的，两者都可以执行一些异步的操作。普通的 function 只能执行同步的操作

**Comment by yuanyuanyuan** [comment]
有个疑问,如果afterFind: async function是异步的话,那么就是异步的异步?因为本身monogolass是异步的,为什么还需要做这种处理?

**Comment by nswbmw** [comment]
这种操作（在 hook 函数里做些异步操作，不如手动 populate user 信息等等）很常见吧，你可以看下 mongoose 插件是怎么做的
