### ISSUE TITLE
二进制字段如何声名

### ISSUE THREAD

**Issue by guerbai** [mongolass/mongolass#28]
首先感谢你的教程和轮子，让我学到了很多东西。
看了N-blog，想要自己练练手，尝试将头像存入库中，但不知如何声名二进制字段，不知是否有所有可声名字段类型的列表之类的。

**Comment by nswbmw** [comment]
Mongolass.Types.Buffer 或者 Mongolass.Types.Mixed，不过头像最好存七牛或者 OSS 之类的吧
