### ISSUE TITLE
mongolass 是否没有一个完整的文档

### ISSUE THREAD

**Issue by aaronshsieh** [mongolass/mongolass#3]
找了下 mongolass 的文档，发现好像没有一个全面的，README.md 是不是有点不全面，是否还需要写一个完整的文档

**Comment by nswbmw** [comment]
近期会在知乎写一篇关于 Mongolass 的文章，会讲讲造轮子的过程。虽然不是文档，但看完差不多就知道 Mongolass 怎么用了，毕竟 Mongolass 的功能还是比较少的（相对于 Mongoose

**Comment by nswbmw** [comment]
@aaronshsieh https://zhuanlan.zhihu.com/p/24308524
