### ISSUE TITLE
存储数组的问题

### ISSUE THREAD

**Issue by Lonezj** [mongolass/mongolass#32]
模型： exports.Collect = mongolass.model('Collect', {
  screenshots: { type: ['string'] }
});
数据： screenshots = ["screenshots1", "screenshots2"];
let collect = {
    screenshots: screenshots
}
为什么会出现 TypeError: ($.screenshots: ["screenshots1","screenshots2"]) ✖ ({"type":["string"]}) at Model.insert? 把定义改为 screenshots: { type: 'array' } 也是出现TypeError。

**Comment by nswbmw** [comment]
使用：

```js
exports.Collect = mongolass.model('Collect', {
  screenshots: [{type: 'string' }]
})
```
