### ISSUE TITLE
populate 处理 数组

### ISSUE THREAD

**Issue by wtxx11** [mongolass/mongolass#33]
exports.blog = mongolass.model('blog', {
    title: {type: 'string'},
    date: {type: 'date'},
    author: {type: 'string'},
    category: [{type: Mongolass.Types.ObjectId, ref: 'blogCategory'}],
    content: {type: 'string'},
    isShow: {type: 'boolean'}
});

 blog
            .find(query)
            .populate({path: 'category', model: 'blogCategory'})
            .sort(sort)
            .skip(skip)
            .limit(limit)
            .exec();
Warning: populate is not work.
**********************************************************************
 blog
            .find(query)
            .populate({path: 'category[0]', model: 'blogCategory'})
            .sort(sort)
            .skip(skip)
            .limit(limit)
            .exec();
Warning:populate just show the array index = 0
*************************************************************************
 blog
            .find(query)
            .populate([{path: 'category', model: 'blogCategory'}])
            .sort(sort)
            .skip(skip)
            .limit(limit)
            .exec();

throw Error
***************************************************************************

PLEASE!How to  use "populate"   when the path is 'array'!!!

**Comment by nswbmw** [comment]
之前不能 populate 数组，mongolass-plugin-populate@0.3.0 添加了这个功能
