### ISSUE TITLE
列表类型时执行$push操作报错

### ISSUE THREAD

**Issue by catnipan** [mongolass/mongolass#34]
Schema如下：
```
const PostTest = mongolass.model('PostTest', {
    title: { type: 'string', required: true },
    tags: [{ type: 'string' }]
})
```

创建一条记录
`PostTest.create({title: "", tags: []}).exec();`

执行$push插入操作
`PostTest.updateOne({title:''}, {$push: {tags: "tag1"}}).exec().then(console.log);`
报错
`(node:38059) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: ($.tags[]: "tag1") ✖(type: array)`

看起来好像是{tags: "tag1"}这个在被验证array？另外：如果把schema的tags改成 `[{ type: Mongolass.Types.ObjectId }]` 的话就能成功$push操作

**Comment by nswbmw** [comment]
mongodb@v3.4.10 下测试没问题
