### ISSUE TITLE
更新model里面数组的问题

### ISSUE THREAD

**Issue by hjx5309** [mongolass/mongolass#36]
//模型
const User = mongolass.model('User', {
    name: {
        type: 'string'
    },
    passport: {
        type: 'string'
    },
    token: {
        type: 'string'
    },
    addCreatedAt:{
        type: 'string'
    },
    attention:[{type: 'string' }]
});
//执行代码
 User .update({ _id: admin._id }, { $addToSet: { attention:"11111" } });

执行完之后，不报错，但是我检查数据库，对应的用户下，并没有添加上attention数组

**Comment by nswbmw** [comment]
添加 `.exec()`
