### ISSUE TITLE
關於 Collection Name 的小寫複數名稱，能否指定 大寫 Collection 

### ISSUE THREAD

**Issue by infinityAlive** [mongolass/mongolass#39]
哈囉～您好
我再使用 mongolass 新增 collection 文檔時，在 model 定義了 name ，
會發現在 db 中，會以小寫並且複數的方式創建新的 collection
請問有別的方式可以指定 collection 完整大寫名稱嗎？
Ex: Switch ===> 會自動轉換成 switches 
但我就是想以 Switch 寫入，請問有好的方式嗎？

感謝～

**Comment by nswbmw** [comment]
好好看 README 啊~

```js
const Switch = mongolass.model('Switch', {
  author: { type: Mongolass.Types.ObjectId }
}, { collName: 'Switch' })
```
