### ISSUE TITLE
beforeXXX 插件能否在 schema 校验之前执行

### ISSUE THREAD

**Issue by zgayjjf** [mongolass/mongolass#45]
由于现在 beforeXXX 插件是在 schema 校验之后执行的，因此如果 Schema 里面定义了一个 required 的字段，但是想在 beforeXXX 里面自动添加的话（而不是在业务代码里面手动添加，例如updated_at之类的），会报错。

因此希望可以将两者的执行顺序进行调整，而且目前来看好像没有其他影响。

**Comment by nswbmw** [comment]
明白你的需求了，为啥不用 `default`?

**Comment by zgayjjf** [comment]
直击灵魂的拷问。
之前没想到 default 可以支持函数。
那目前来看应该是没问题了。

感谢！
Issue 我关了
