### ISSUE TITLE
你好，请问还有计划为本项目添加.d.ts吗？我看一年过去了也没有完工，是不是鸽了

### ISSUE THREAD

**Issue by CaoMeiYouRen** [mongolass/mongolass#46]
没有类型提示确实有点难用啊
像model()返回的是any类型，搞不清楚有几个方法，很容易手滑写错了。
![image](https://ws3.sinaimg.cn/mw690/006W7JQLly1g62mskou5gj30lm02mq31.jpg)
而mongoose中的model()返回的带类型，这样也方便调用。
![image](https://ws1.sinaimg.cn/mw690/006W7JQLly1g62mv9pyuoj30wn09rgnx.jpg)

**Comment by nswbmw** [comment]
咳咳..创业中..

**Comment by CaoMeiYouRen** [comment]
> 咳咳..创业中..

那好吧，我去找找看别的项目。。。
