### ISSUE TITLE
query $elemMatch 不生效

### ISSUE THREAD

**Issue by SaltFish001** [mongolass/mongolass#49]
`let data = await blocktemps.find(
    { "blocks": { '$elemMatch':{ "id": "1-2" }}}
  ).exec();`
该语句使用mongolass查询不生效，依旧会返回blocks下所有数组。
使用命令行则能正确返回指定数组元素
版本：` mongolass": "^4.4.5`

**Comment by nswbmw** [comment]
能把blocktemps表里数据列一些出来吗？

**Comment by SaltFish001** [comment]
> 能把blocktemps表里数据列一些出来吗？

我找到解决办法了，不能直接在find()里面写筛选条件，需要将条件写入select()里面才会执行
