### ISSUE TITLE
嵌套对象验证无效

### ISSUE THREAD

**Issue by SaltFish001** [mongolass/mongolass#50]
```
  chartData_t: {
    Color: { type: Mongolass.Types.String, require: true, default: 'red' },
    Title: { type: Mongolass.Types.String, require: true, default: '实时温度图' },
    MaxY: { type: Mongolass.Types.Number, require: true, default: 50 },
    MinY: { type: Mongolass.Types.Number, require: true, default: -10 },
    Yname: { type: Mongolass.Types.String, require: true, default: '温度' },
    Xname: { type: Mongolass.Types.String, require: true, default: '点位' },
  }
```
这是我的Schema
 ```
 chartData_t: {
      "Color": 'red',
      "Title": "机械信号",
      "MaxY": 50,
      MinY:0,
      "Yname": {m:"幅值"},
      "Xname": "点位"
    }
```
这是我测试的值，没有报错，直接存进去了

**Comment by SaltFish001** [comment]
注意Yname

**Comment by nswbmw** [comment]
你需要用：

```
Yname: { type: 'string', require: true, default: '温度' },
```

即：用 type: 'string' 而不是 Mongolass.Types.String。因为后者会尝试转换成 String 类型（所以 {m:"幅值"}被转换成了'[object Object]'），只有转换失败才会抛出错误。

**Comment by SaltFish001** [comment]
> 你需要用：
> 
> ```
> Yname: { type: 'string', require: true, default: '温度' },
> ```
> 
> 即：用 type: 'string' 而不是 Mongolass.Types.String。因为后者会尝试转换成 String 类型（所以 {m:"幅值"}被转换成了'[object Object]'），只有转换失败才会抛出错误。

不，数据库保存的不是字符串，而是一个对象，我一会儿到家把数据库截图发给你看

**Comment by nswbmw** [comment]
![image](https://user-images.githubusercontent.com/4279697/70795590-1d9b9400-1ddb-11ea-8aea-7c2219438545.png)
是最新版本 v4.4.6 吗

**Comment by SaltFish001** [comment]
> ![image](https://user-images.githubusercontent.com/4279697/70795590-1d9b9400-1ddb-11ea-8aea-7c2219438545.png)
> 是最新版本 v4.4.6 吗

package.json显示的是4.4.6我回去再看看
