### ISSUE TITLE
强制检查域的存在

### ISSUE THREAD

**Issue by jiang-wei** [mongolass/mongolass#7]
mongolass.model() 语句定义了 `schema`
在 model.create(obj) 似乎在 obj 的域比 schema 定义的要少的时候仍能够创建记录。
什么办法能够保证或检查 obj 中的域和 schema 是一致的再真正存入？

**Comment by nswbmw** [comment]
目前做不到，因为实现起来比较困难，你可以去了解下 another-json-schema 的实现（目前个人不太满意，不过感觉改不动了..），欢迎 pr..

**Comment by jiang-wei** [comment]
好吧
那我只能手动检查了
